version: '3.1'

services:

    db:
        image: postgres:13.0-alpine
        environment:
          - POSTGRES_DB=db_name
          - POSTGRES_USER=db_user
          - POSTGRES_PASSWORD=db_pwd
        volumes:
          - collector_data:/var/lib/postgresql/data/

    web:
        build: project/
        restart: always
        volumes:
          - static_value:/app/static/
          - media_value:/app/media/
        depends_on:
          - db

    webserver:
        image: 'nginx:alpine'
        working_dir: /var/www
        volumes:
            - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - static_value:/var/html/static/
            - media_value:/var/html/media/
        ports:
            - '80:80'
        depends_on:
            - web

volumes:
  static_value:
  media_value:
  collector_data: