# Generated by Django 4.2.11 on 2024-03-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название сбора')),
                ('reason', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('funeral', 'Похороны')], max_length=32, verbose_name='Повод')),
                ('description', models.TextField(max_length=320, verbose_name='Описание сбора')),
                ('total', models.PositiveIntegerField(blank=True, verbose_name='Сумма для сбора')),
                ('current', models.PositiveIntegerField(blank=True, verbose_name='Собрано средств')),
                ('donaters_cnt', models.PositiveSmallIntegerField(verbose_name='Количество донатов')),
                ('image', models.ImageField(blank=True, help_text='Место для кратинки', upload_to='events/', verbose_name='Картинка')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Начало сбора')),
                ('end', models.DateTimeField(help_text='гггг-мм-дд ч:м', verbose_name='Срок')),
            ],
            options={
                'verbose_name': 'Сбор',
                'verbose_name_plural': 'Сборы',
                'ordering': ('-end',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collect')),
            ],
            options={
                'verbose_name': 'Внесение денег',
                'verbose_name_plural': 'Донаты',
            },
        ),
    ]
