# Generated by Django 4.2.11 on 2024-03-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='donaters',
            field=models.ManyToManyField(blank=True, to='main.payment'),
        ),
    ]
