# Generated by Django 4.2.11 on 2024-03-11 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_collect_current_alter_collect_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='donaters_cnt',
        ),
    ]
